[meta]
version = "4.0.5-beta (2023-09-21)"
name = "Bingo (Beta)"
author = "TheGeekid"
category = "Game"
siteid = 410

[script]
exports = ["src/export/definitions.as"]
shared_exports = ["src/export/shared.as"]
