[meta]
version = "4.0-dev"
name = "Bingo"
author = "TheGeekid"
category = "Game"
siteid = 271

[script]
timeout = 10000
exports = ["src/export/definitions.as"]
shared_exports = ["src/export/shared.as"]
