[meta]
version = "4.0-beta (2023-08-10)"
name = "Bingo (Beta)"
author = "TheGeekid"
category = "Game"
siteid = 410

[script]
timeout = 10000
exports = ["src/export/definitions.as"]
shared_exports = ["src/export/shared.as"]
