[project]
name = "mapcache"
version = "1.0.0"
description = "simple TrackmaniaExchange map metadata exporter."
requires-python = ">=3.10"
authors = ["Geekid"]
license = "GPLv3"
dependencies = [
    "requests>=2.28.2"
]
