[project]
name = "bingoserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.10.5",
    "fastapi[standard]>=0.114.0",
    "ruff>=0.6.4",
    "sqlmodel>=0.0.22",
]

[tool.setuptools]
py-modules = []
