// This file is automatically @generated by the `typegen` tool.
// Do not manually edit it! See `common/types.xml` for details.
use serde::{Serialize, Deserialize};


/* It's the first type. */
#[derive(Serialize, Deserialize, Debug)]
pub struct TypeFirst {
    pub value: i32,
	pub other: u32
}


#[derive(Serialize, Deserialize, Debug)]
pub struct TypeSecond {
    pub text: String
}


/* This struct has more complex members. */
#[derive(Serialize, Deserialize, Debug)]
pub struct Complex {
    pub one: Vec<i32>,
	pub two: Option<String>,
	pub three: Option<Vec<TypeFirst>>
}
